[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
seeds = false
skip-lint = false

[programs.localnet]
coffee_exchange = "9VdKGKXs5ZJd6Cr9GtJcPP8fdUSmRgvkYScvhi1oPkFc"

[programs.devnet]
coffee_exchange = "9VdKGKXs5ZJd6Cr9GtJcPP8fdUSmRgvkYScvhi1oPkFc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"




